spring.application.name=studentmgmt

server.port=${PORT:8080}

spring.data.mongodb.uri=mongodb+srv://stdmgmtdbuser:Pn2fAQCMUb2IKv3o@cluster0.igf2mcw.mongodb.net/stdmgmtdb?retryWrites=true&w=majority

spring.data.mongodb.auto-index-creation=true
